name = "public-bucket"
main = "./dist/worker.mjs"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
r2_buckets = [{ binding = "BUCKET", bucket_name = "carpark-dev-0" }]

[build]
command = "npm run build"

[vars]
DEBUG = "true"
FF_TELEMETRY_ENABLED = "false"

# PROD!
[env.carpark-production]
account_id = "fffa4b4363a7e5250af8357087263b3a"
r2_buckets = [{ binding = "BUCKET", bucket_name = "carpark-prod-0" }]
route = { pattern = "https://carpark-prod-0.r2.w3s.link/*", zone_id = "ae60d8f737317467ec666dc3851a6277" }

[env.carpark-production.vars]
DEBUG = "false"
FF_TELEMETRY_ENABLED = "true"

[env.carpark-production-1]
account_id = "fffa4b4363a7e5250af8357087263b3a"
r2_buckets = [{ binding = "BUCKET", bucket_name = "carpark-prod-1" }]
route = { pattern = "https://carpark-prod-1.r2.w3s.link/*", zone_id = "ae60d8f737317467ec666dc3851a6277" }

[env.carpark-production-1.vars]
DEBUG = "false"
FF_TELEMETRY_ENABLED = "true"

# STAGING!
[env.carpark-staging]
account_id = "fffa4b4363a7e5250af8357087263b3a"
r2_buckets = [{ binding = "BUCKET", bucket_name = "carpark-staging-0" }]
route = { pattern = "https://carpark-staging-0.r2.w3s.link/*", zone_id = "ae60d8f737317467ec666dc3851a6277" }

[env.carpark-staging.vars]
FF_TELEMETRY_ENABLED = "true"
DEBUG = "true"

# HANNAH DEV TESTING!
[env.hannahhoward]
account_id = "fffa4b4363a7e5250af8357087263b3a"
r2_buckets = [{ binding = "BUCKET", bucket_name = "carpark-prod-0", preview_bucket_name = "carpark-prod-0" }]
route = { pattern = "https://carpark-hannah-0.r2.w3s.link/*", zone_id = "ae60d8f737317467ec666dc3851a6277" }

[env.hannahhoward.vars]
FF_TELEMETRY_ENABLED = "true"
DEBUG = "true"